/* -----------------------------------------------------------------------------
 *  ________              __     __ _______         __
 * |  |  |  |.-----.----.|  |.--|  |   |   |.---.-.|  |--.-----.----.
 * |  |  |  ||  _  |   _||  ||  _  |       ||  _  ||    <|  -__|   _|
 * |________||_____|__|  |__||_____|__|_|__||___._||__|__|_____|__|
 *
 * Part of MiddleWar project.
 * -----------------------------------------------------------------------------
 * File    : business.SurfaceType.java
 *
 * History :
 * 1.0     : Add to wm
 *
 */

package middlewar.server.worldmaker.business;

/**
 * Every types of surfaces
 * @author Higurashi
 * @version WM 1.0
 * @since WM 1.0
 */
public enum SurfaceType {


none(new SurfaceTypeSetBasic(
           BlockType.surface_default_C_I,
           BlockType.surface_default_C_E,
           BlockType.surface_default_N,
           BlockType.surface_default_S,
           BlockType.surface_default_E,
           BlockType.surface_default_O,
           BlockType.surface_default_SO,
           BlockType.surface_default_NO,
           BlockType.surface_default_SE,
           BlockType.surface_default_NE,
           BlockType.surface_default_NO_I,
           BlockType.surface_default_NE_I,
           BlockType.surface_default_SO_I,
           BlockType.surface_default_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.surface_default_N_M,
           BlockType.surface_default_S_M,
           BlockType.surface_default_E_M,
           BlockType.surface_default_O_M,
           BlockType.surface_default_V_M,
           BlockType.surface_default_H_M,
           BlockType.surface_default_C_M,
           BlockType.surface_default_HV_M,
           BlockType.surface_default_NE_M,
           BlockType.surface_default_SE_M,
           BlockType.surface_default_NO_M,
           BlockType.surface_default_SO_M,
           BlockType.surface_default_NE_H_M,
           BlockType.surface_default_SE_H_M,
           BlockType.surface_default_NO_H_M,
           BlockType.surface_default_SO_H_M,
           BlockType.surface_default_NE_V_M,
           BlockType.surface_default_SE_V_M,
           BlockType.surface_default_NO_V_M,
           BlockType.surface_default_SO_V_M,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.surface_default_N_U,
           BlockType.surface_default_S_U,
           BlockType.surface_default_E_U,
           BlockType.surface_default_O_U,
           BlockType.surface_default_NE_U,
           BlockType.surface_default_SE_U,
           BlockType.surface_default_NO_U,
           BlockType.surface_default_SO_U,
           BlockType.surface_default_NE_I_U,
           BlockType.surface_default_SE_I_U,
           BlockType.surface_default_NO_I_U,
           BlockType.surface_default_SO_I_U,
           BlockType.surface_default_SS,
           BlockType.surface_default_SSE,
           BlockType.surface_default_SSO,
           BlockType.surface_default_S_D,
           BlockType.surface_default_SE_D,
           BlockType.surface_default_SO_D,
           BlockType.surface_default_OO,
           BlockType.surface_default_ONO,
           BlockType.surface_default_OSO,
           BlockType.surface_default_EE,
           BlockType.surface_default_ENE,
           BlockType.surface_default_ESE
           )
),


heaven_1(new SurfaceTypeSetBasic(
           BlockType.heaven_1_C_I,
           BlockType.invisible,
           BlockType.heaven_1_N,
           BlockType.heaven_1_S,
           BlockType.heaven_1_E,
           BlockType.heaven_1_O,
           BlockType.heaven_1_SO,
           BlockType.heaven_1_NO,
           BlockType.heaven_1_SE,
           BlockType.heaven_1_NE,
           BlockType.heaven_1_NO_I,
           BlockType.heaven_1_NE_I,
           BlockType.heaven_1_SO_I,
           BlockType.heaven_1_SE_I
           )
),

interior_1(new SurfaceTypeSetBasic(
           BlockType.interior_1_C_I,
           BlockType.interior_1_C_E,
           BlockType.interior_1_N,
           BlockType.interior_1_S,
           BlockType.interior_1_E,
           BlockType.interior_1_O,
           BlockType.interior_1_SO,
           BlockType.interior_1_NO,
           BlockType.interior_1_SE,
           BlockType.interior_1_NE,
           BlockType.interior_1_NO_I,
           BlockType.interior_1_NE_I,
           BlockType.interior_1_SO_I,
           BlockType.interior_1_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.interior_1_N_M,
           BlockType.interior_1_S_M,
           BlockType.interior_1_E_M,
           BlockType.interior_1_O_M,
           BlockType.interior_1_V_M,
           BlockType.interior_1_H_M,
           BlockType.interior_1_C_M,
           BlockType.interior_1_HV_M,
           BlockType.interior_1_NE_M,
           BlockType.interior_1_SE_M,
           BlockType.interior_1_NO_M,
           BlockType.interior_1_SO_M,
           BlockType.interior_1_NE_H_M,
           BlockType.interior_1_SE_H_M,
           BlockType.interior_1_NO_H_M,
           BlockType.interior_1_SO_H_M,
           BlockType.interior_1_NE_V_M,
           BlockType.interior_1_SE_V_M,
           BlockType.interior_1_NO_V_M,
           BlockType.interior_1_SO_V_M,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.interior_1_N,
           BlockType.interior_1_S,
           BlockType.interior_1_E,
           BlockType.interior_1_O,
           BlockType.interior_1_NE,
           BlockType.interior_1_SE,
           BlockType.interior_1_NO,
           BlockType.interior_1_SO,
           BlockType.interior_1_NE_I,
           BlockType.interior_1_SE_I,
           BlockType.interior_1_NO_I,
           BlockType.interior_1_SO_I,
           BlockType.interior_1_SS,
           BlockType.interior_1_SSE,
           BlockType.interior_1_SSO,
           BlockType.interior_1_S_D,
           BlockType.interior_1_SE_D,
           BlockType.interior_1_SO_D,
           null,
           null,
           null,
           null,
           null,
           null
           )
),

grass_1(new SurfaceTypeSetBasic(
           BlockType.grass_C_I,
           BlockType.dev_unknown,
           BlockType.grass_N,
           BlockType.grass_S,
           BlockType.grass_E,
           BlockType.grass_O,
           BlockType.grass_SO,
           BlockType.grass_NO,
           BlockType.grass_SE,
           BlockType.grass_NE,
           BlockType.grass_NO_I,
           BlockType.grass_NE_I,
           BlockType.grass_SO_I,
           BlockType.grass_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.grass_C_M,
           BlockType.grass_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.grass_N_U,
           BlockType.grass_S_U,
           BlockType.grass_E_U,
           BlockType.grass_O_U,
           BlockType.grass_NE_U,
           BlockType.grass_SE_U,
           BlockType.grass_NO_U,
           BlockType.grass_SO_U,
           BlockType.grass_NE_I_U,
           BlockType.grass_SE_I_U,
           BlockType.grass_NO_I_U,
           BlockType.grass_SO_I_U,
           BlockType.grass_SS,
           BlockType.grass_SSE,
           BlockType.grass_SSO,
           BlockType.grass_S_D,
           BlockType.grass_SE_D,
           BlockType.grass_SO_D,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible
           )
),

grass_2(new SurfaceTypeSetBasic(
           BlockType.grass_C_I,
           BlockType.dev_uu,
           BlockType.grass_2_N,
           BlockType.grass_2_S,
           BlockType.grass_2_E,
           BlockType.grass_2_O,
           BlockType.grass_2_SO,
           BlockType.grass_2_NO,
           BlockType.grass_2_SE,
           BlockType.grass_2_NE,
           BlockType.grass_NO_I,
           BlockType.grass_NE_I,
           BlockType.grass_SO_I,
           BlockType.grass_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.grass_2_C_M,
           BlockType.grass_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.grass_N_U,
           BlockType.grass_S_U,
           BlockType.grass_E_U,
           BlockType.grass_O_U,
           BlockType.grass_NE_U,
           BlockType.grass_SE_U,
           BlockType.grass_NO_U,
           BlockType.grass_SO_U,
           BlockType.grass_NE_I_U,
           BlockType.grass_SE_I_U,
           BlockType.grass_NO_I_U,
           BlockType.grass_SO_I_U,
           BlockType.grass_SS,
           BlockType.grass_SSE,
           BlockType.grass_SSO,
           BlockType.grass_2_S_D,
           BlockType.grass_2_SE_D,
           BlockType.grass_2_SO_D,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo
           )
),

grass_3(new SurfaceTypeSetBasic(
           BlockType.grass_C_I,
           BlockType.dev_uu,
           BlockType.grass_N,
           BlockType.grass_S,
           BlockType.grass_E,
           BlockType.grass_O,
           BlockType.grass_SO,
           BlockType.grass_NO,
           BlockType.grass_SE,
           BlockType.grass_NE,
           BlockType.grass_NO_I,
           BlockType.grass_NE_I,
           BlockType.grass_SO_I,
           BlockType.grass_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.grass_C_M,
           BlockType.grass_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.grass_N_U,
           BlockType.grass_S_U,
           BlockType.grass_E_U,
           BlockType.grass_O_U,
           BlockType.grass_NE_U,
           BlockType.grass_SE_U,
           BlockType.grass_NO_U,
           BlockType.grass_SO_U,
           BlockType.grass_NE_I_U,
           BlockType.grass_SE_I_U,
           BlockType.grass_NO_I_U,
           BlockType.grass_SO_I_U,
           BlockType.grass_SS,
           BlockType.grass_SSE,
           BlockType.grass_SSO,
           BlockType.grass_3_S_D,
           BlockType.grass_3_SE_D,
           BlockType.grass_3_SO_D,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible,
           BlockType.invisible
           )
),

grass_4(new SurfaceTypeSetBasic(
           BlockType.grass_4_C_I,
           BlockType.invisible,
           BlockType.grass_4_N,
           BlockType.grass_4_S,
           BlockType.grass_4_E,
           BlockType.grass_4_O,
           BlockType.grass_4_SO,
           BlockType.grass_4_NO,
           BlockType.grass_4_SE,
           BlockType.grass_4_NE,
           BlockType.grass_4_NO_I,
           BlockType.grass_4_NE_I,
           BlockType.grass_4_SO_I,
           BlockType.grass_4_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.grass_4_N_M,
           BlockType.grass_4_S_M,
           BlockType.grass_4_E_M,
           BlockType.grass_4_O_M,
           BlockType.grass_4_V_M,
           BlockType.grass_4_H_M,
           BlockType.grass_4_C_M,
           BlockType.grass_4_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           )
),
ground_1(new SurfaceTypeSetBasic(
           BlockType.ground_1_C_I,
           BlockType.grass_C_I,
           BlockType.ground_1_N,
           BlockType.ground_1_S,
           BlockType.ground_1_E,
           BlockType.ground_1_O,
           BlockType.ground_1_SO,
           BlockType.ground_1_NO,
           BlockType.ground_1_SE,
           BlockType.ground_1_NE,
           BlockType.ground_1_NO_I,
           BlockType.ground_1_NE_I,
           BlockType.ground_1_SO_I,
           BlockType.ground_1_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.ground_1_C_M,
           BlockType.ground_1_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           )
),

water_1_A(new SurfaceTypeSetBasic(
           BlockType.water_1_A_C_I,
           BlockType.grass_C_I,
           BlockType.water_1_A_N,
           BlockType.water_1_A_S,
           BlockType.water_1_A_E,
           BlockType.water_1_A_O,
           BlockType.water_1_A_SO,
           BlockType.water_1_A_NO,
           BlockType.water_1_A_SE,
           BlockType.water_1_A_NE,
           BlockType.water_1_A_NO_I,
           BlockType.water_1_A_NE_I,
           BlockType.water_1_A_SO_I,
           BlockType.water_1_A_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.water_1_A_C_M,
           BlockType.water_1_A_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null
           )
),

deamon_1(new SurfaceTypeSetBasic(
           BlockType.deamon_1_C_I,
           BlockType.deamon_1_C_E,
           BlockType.deamon_1_C_E,
           BlockType.deamon_1_C_E,
           BlockType.deamon_1_C_E,
           BlockType.deamon_1_C_E,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.deamon_1_N_U,
           BlockType.deamon_1_S_U,
           BlockType.deamon_1_E_U,
           BlockType.deamon_1_O_U,
           BlockType.deamon_1_NE_U,
           BlockType.deamon_1_SE_U,
           BlockType.deamon_1_NO_U,
           BlockType.deamon_1_SO_U,
           BlockType.deamon_1_NE_I_U,
           BlockType.deamon_1_SE_I_U,
           BlockType.deamon_1_NO_I_U,
           BlockType.deamon_1_SO_I_U,
           BlockType.deamon_1_SS,
           BlockType.deamon_1_SSE,
           BlockType.deamon_1_SSO,
           BlockType.deamon_1_S_D,
           BlockType.deamon_1_SE_D,
           BlockType.deamon_1_SO_D,
           BlockType.deamon_1_OO,
           BlockType.deamon_1_ONO,
           BlockType.deamon_1_OSO,
           BlockType.deamon_1_EE,
           BlockType.deamon_1_ENE,
           BlockType.deamon_1_ESE
           )
),

deamon_2(new SurfaceTypeSetBasic(
           BlockType.deamon_2_C_I,
           BlockType.deamon_2_C_E,
           BlockType.deamon_2_C_I,
           BlockType.deamon_2_C_I,
           BlockType.deamon_2_E,
           BlockType.deamon_2_O,
           BlockType.deamon_2_SO,
           BlockType.deamon_2_NO,
           BlockType.deamon_2_SE,
           BlockType.deamon_2_NE,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.deamon_2_N_U,
           BlockType.deamon_2_S_U,
           BlockType.deamon_2_E_U,
           BlockType.deamon_2_O_U,
           BlockType.deamon_2_NE_U,
           BlockType.deamon_2_SE_U,
           BlockType.deamon_2_NO_U,
           BlockType.deamon_2_SO_U,
           BlockType.deamon_2_NE_I_U,
           BlockType.deamon_2_SE_I_U,
           BlockType.deamon_2_NO_I_U,
           BlockType.deamon_2_SO_I_U,
           BlockType.deamon_2_SS,
           BlockType.deamon_2_SSE,
           BlockType.deamon_2_SSO,
           BlockType.deamon_2_S_D,
           BlockType.deamon_2_SE_D,
           BlockType.deamon_2_SO_D,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo,
           BlockType.dev_todo
           )
),

town_ground_1(new SurfaceTypeSetBasic(
           BlockType.town_ground_1_C_I,
           BlockType.dev_uu,
           BlockType.town_ground_1_N,
           BlockType.town_ground_1_S,
           BlockType.town_ground_1_E,
           BlockType.town_ground_1_O,
           BlockType.town_ground_1_SO,
           BlockType.town_ground_1_NO,
           BlockType.town_ground_1_SE,
           BlockType.town_ground_1_NE,
           BlockType.town_ground_1_NO_I,
           BlockType.town_ground_1_NE_I,
           BlockType.town_ground_1_SO_I,
           BlockType.town_ground_1_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.dev_uu,
           BlockType.town_ground_1_C_M,
           BlockType.town_ground_1_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           )
),

town_ground_4(new SurfaceTypeSetBasic(
           BlockType.town_ground_4_C_I,
           null,
           BlockType.town_ground_4_N,
           BlockType.town_ground_4_S,
           BlockType.town_ground_4_E,
           BlockType.town_ground_4_O,
           BlockType.town_ground_4_SO,
           BlockType.town_ground_4_NO,
           BlockType.town_ground_4_SE,
           BlockType.town_ground_4_NE,
           BlockType.town_ground_4_NO_I,
           BlockType.town_ground_4_NE_I,
           BlockType.town_ground_4_SO_I,
           BlockType.town_ground_4_SE_I
           ),
           new SurfaceTypeSetExtended(
           BlockType.town_ground_4_N_M,
           BlockType.town_ground_4_S_M,
           BlockType.town_ground_4_E_M,
           BlockType.town_ground_4_O_M,
           BlockType.town_ground_4_V_M,
           BlockType.town_ground_4_H_M,
           BlockType.town_ground_4_C_M,
           BlockType.town_ground_4_HV_M,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           null,
           BlockType.surface_default_E_V_M,
           BlockType.surface_default_O_V_M,
           BlockType.surface_default_N_H_M,
           BlockType.surface_default_S_H_M
           ),
           new SurfaceTypeSetLevel(
           BlockType.deamon_2_N_U,
           BlockType.deamon_2_S_U,
           BlockType.deamon_2_E_U,
           BlockType.deamon_2_O_U,
           BlockType.deamon_2_NE_U,
           BlockType.deamon_2_SE_U,
           BlockType.deamon_2_NO_U,
           BlockType.deamon_2_SO_U,
           BlockType.deamon_2_NE_I_U,
           BlockType.deamon_2_SE_I_U,
           BlockType.deamon_2_NO_I_U,
           BlockType.deamon_2_SO_I_U,
           BlockType.deamon_2_SS,
           BlockType.deamon_2_SSE,
           BlockType.deamon_2_SSO,
           BlockType.deamon_2_S_D,
           BlockType.deamon_2_SE_D,
           BlockType.deamon_2_SO_D,
           null,
           null,
           null,
           null,
           null,
           null
           )
);


/*
grass(new SurfaceTypeSet(BlockType.grass_C,
                         BlockType.dev_todo,
                         BlockType.grass_N,
                         BlockType.grass_S,
                         BlockType.grass_E,
                         BlockType.grass_O,
                         BlockType.grass_SO,
                         BlockType.grass_NO,
                         BlockType.grass_SE,
                         BlockType.grass_NE,
                         BlockType.grass_SO_I,
                         BlockType.grass_NO_I,
                         BlockType.grass_SE_I,
                         BlockType.grass_NE_I,
                         BlockType.grass_mini,
                         BlockType.grass_cross,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo
                         )),

grass_2(new SurfaceTypeSet(BlockType.grass_2_C,
                           BlockType.dev_todo,
                           BlockType.grass_2_N,
                           BlockType.grass_2_S,
                           BlockType.grass_2_E,
                           BlockType.grass_2_O,
                           BlockType.grass_2_SO,
                           BlockType.grass_2_NO,
                           BlockType.grass_2_SE,
                           BlockType.grass_2_NE,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo,
                           BlockType.dev_todo)),

town_ground_1_grass(new SurfaceTypeSet(BlockType.town_ground_1_C,
                                       BlockType.dev_todo,
                                       BlockType.town_ground_1_N_grass,
                                       BlockType.town_ground_1_S_grass,
                                       BlockType.town_ground_1_E_grass,
                                       BlockType.town_ground_1_O_grass,
                                       BlockType.town_ground_1_SO_grass,
                                       BlockType.town_ground_1_NO_grass,
                                       BlockType.town_ground_1_SE_grass,
                                       BlockType.town_ground_1_NE_grass,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.town_ground_1_mini_grass,
                                       BlockType.town_ground_1_cross_grass,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo,
                                       BlockType.dev_todo)),

town_ground_2(new SurfaceTypeSet(BlockType.town_ground_2_C,
                                 BlockType.dev_todo,
                                 BlockType.town_ground_2_N,
                                 BlockType.town_ground_2_S,
                                 BlockType.town_ground_2_E,
                                 BlockType.town_ground_2_O,
                                 BlockType.town_ground_2_SO,
                                 BlockType.town_ground_2_NO,
                                 BlockType.town_ground_2_SE,
                                 BlockType.town_ground_2_NE,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo)),

town_ground_3(new SurfaceTypeSet(BlockType.town_ground_3_C,
                                 BlockType.dev_todo,
                                 BlockType.town_ground_3_N,
                                 BlockType.town_ground_3_S,
                                 BlockType.town_ground_3_E,
                                 BlockType.town_ground_3_O,
                                 BlockType.town_ground_3_SO,
                                 BlockType.town_ground_3_NO,
                                 BlockType.town_ground_3_SE,
                                 BlockType.town_ground_3_NE,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo)),

grass_coast(new SurfaceTypeSet(BlockType.invisible,
                               BlockType.dev_todo,
                               BlockType.grass_coast_N,
                               BlockType.grass_coast_S,
                               BlockType.grass_coast_E,
                               BlockType.grass_coast_O,
                               BlockType.grass_coast_SO,
                               BlockType.grass_coast_NO,
                               BlockType.grass_coast_SE,
                               BlockType.grass_coast_NE,
                               BlockType.grass_coast_SO_I,
                               BlockType.grass_coast_NO_I,
                               BlockType.grass_coast_SE_I,
                               BlockType.grass_coast_NE_I,
                               BlockType.grass_coast_mini,
                               BlockType.grass_coast_cross,
                               BlockType.dev_todo,
                               BlockType.dev_todo,
                               BlockType.dev_todo,
                               BlockType.dev_todo,
                               BlockType.dev_todo,
                               BlockType.dev_todo)),

grass_coast_2(new SurfaceTypeSet(BlockType.grass_C,
                                 BlockType.dev_todo,
                                 BlockType.grass_coast_2_N,
                                 BlockType.grass_coast_2_S,
                                 BlockType.grass_coast_2_E,
                                 BlockType.grass_coast_2_O,
                                 BlockType.grass_coast_2_SO,
                                 BlockType.grass_coast_2_NO,
                                 BlockType.grass_coast_2_SE,
                                 BlockType.grass_coast_2_NE,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.grass_coast_2_mini,
                                 BlockType.grass_coast_2_cross,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo,
                                 BlockType.dev_todo)),

water(new SurfaceTypeSet(BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo,
                         BlockType.dev_todo)),

desert(new SurfaceTypeSet(BlockType.desert_C,
                          BlockType.dev_todo,
                          BlockType.grass_N,
                          BlockType.grass_S,
                          BlockType.grass_E,
                          BlockType.grass_O,
                          BlockType.grass_SO,
                          BlockType.grass_NO,
                          BlockType.grass_SE,
                          BlockType.grass_NE,
                          BlockType.grass_SO_I,
                          BlockType.grass_NO_I,
                          BlockType.grass_SE_I,
                          BlockType.grass_NE_I,
                          BlockType.grass_mini,
                          BlockType.grass_cross,
                          BlockType.dev_todo,
                          BlockType.dev_todo,
                          BlockType.dev_todo,
                          BlockType.dev_todo,
                          BlockType.dev_todo,
                          BlockType.dev_todo)),

rock(new SurfaceTypeSet(BlockType.grass_C,
                        BlockType.dev_todo,
                        BlockType.grass_N,
                        BlockType.grass_S,
                        BlockType.grass_E,
                        BlockType.grass_O,
                        BlockType.grass_SO,
                        BlockType.grass_NO,
                        BlockType.grass_SE,
                        BlockType.grass_NE,
                        BlockType.grass_SO_I,
                        BlockType.grass_NO_I,
                        BlockType.grass_SE_I,
                        BlockType.grass_NE_I,
                        BlockType.grass_mini,
                        BlockType.grass_cross,
                        BlockType.dev_todo,
                        BlockType.dev_todo,
                        BlockType.dev_todo,
                        BlockType.dev_todo,
                        BlockType.dev_todo,
                        BlockType.dev_todo));
*/


    private SurfaceTypeSetBasic basicSet;
    private SurfaceTypeSetExtended extendedSet;
    private SurfaceTypeSetLevel levelSet;

    public final SurfaceTypeSetExtended DEFAULT_EXTENDED =
    new SurfaceTypeSetExtended(BlockType.dev_unknown, BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown,BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown,BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown,BlockType.dev_unknown, BlockType.dev_unknown,
                               BlockType.dev_unknown, BlockType.dev_unknown,BlockType.dev_unknown, BlockType.dev_unknown);


    public final SurfaceTypeSetLevel DEFAULT_LEVEL =
    new SurfaceTypeSetLevel(BlockType.dev_unknown, BlockType.dev_unknown_up, BlockType.dev_unknown,
                            BlockType.dev_unknown, BlockType.dev_unknown, BlockType.dev_unknown_up,
                            BlockType.dev_unknown, BlockType.dev_unknown_up, BlockType.dev_unknown, 
                            BlockType.dev_unknown_up, BlockType.dev_unknown, BlockType.dev_unknown,
                            BlockType.dev_unknown_up_down, BlockType.dev_unknown_up_down,
                            BlockType.dev_unknown_up_down, BlockType.dev_unknown_down,
                            BlockType.dev_unknown_down, BlockType.dev_unknown_down,
                            BlockType.dev_unknown_down, BlockType.dev_unknown_down,BlockType.dev_unknown_down,
                            BlockType.dev_unknown_down, BlockType.dev_unknown_down,BlockType.dev_unknown_down);

    private SurfaceType(SurfaceTypeSetBasic basicSet) {
        this.basicSet = basicSet;
        this.extendedSet = DEFAULT_EXTENDED;
        this.levelSet = DEFAULT_LEVEL;
    }

    private SurfaceType(SurfaceTypeSetBasic basicSet,
                        SurfaceTypeSetExtended extendedSet) {
        this.basicSet = basicSet;
        this.extendedSet = extendedSet;
        this.levelSet = DEFAULT_LEVEL;
    }

    private SurfaceType(SurfaceTypeSetBasic basicSet,
                        SurfaceTypeSetExtended extendedSet,
                        SurfaceTypeSetLevel levelSet) {
        this.basicSet = basicSet;
        this.extendedSet = extendedSet;
        this.levelSet = levelSet;
    }

    public SurfaceTypeSetBasic getBasicSet() {
        return basicSet;
    }

    public SurfaceTypeSetExtended getExtendedSet() {
        return extendedSet;
    }

    public SurfaceTypeSetLevel getLevelSet() {
        return levelSet;
    }


}
